config/routes.rb
Rails.application.routes.draw do
  get 'flights/search'
  resources :flight_prices
  resources :flights do
    # resources :flight_prices
  end
  resources :users
  get 'welcome/index'
  get 'articles/new'
  get 'articles/download'
  get 'articles/preview'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :articles do
    resources :comments
  end
  root 'welcome#index'
end

app/models/flight.rb
class Flight
  include Mongoid::Document

  has_one :flight_price

  field :flight_code, type: String
  field :sched, type: String
  field :from, type: String
  field :to, type: String

  def find_by_where(from, to)
    Flight.where(from: from, "to": to)
  end

  def in_code(codes)
    Flight.in(flight_code: codes)
    # flight = Flight.in("flight_code": codes).order_by("sched")
    # binding.pry
  end

  private

  def find_by_code(code)
    Flight.find_by(flight_code: code)
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: [:show, :edit, :update, :destroy]

  # GET /flights
  # GET /flights.json
  def index
    @flights = Flight.all
  end

  # GET /flights/1
  # GET /flights/1.json
  def show
  end

  # GET /flights/new
  def new
    @flight = Flight.new
  end

  # GET /flights/1/edit
  def edit
  end

  def search
    print params[:date]
    flight = Flight.new
    # from chnegdu  to xi'an
    from_flights = flight.find_by_where('Chengdu', 'Xi\'an')
    # flight codes
    codes = from_flights.map(&:flight_code)
    # map(&:) 可以替代 each
    # codes = []
    # from_flights.each do |f|
    #   codes << f.flight_code
    # end
    flight_price = FlightPrice.new
    # min price and detail
    from_combine = flight_price.find_by_combine(params[:type], params[:date], codes)
    from_flight_price = from_combine[:flights]
    codes = from_flight_price.map(&:flight_code)
    # codes = []
    # from_flight_price.each do |f|
    #   codes << f.flight_code
    # end
    # detail flights
    from_flights = flight.in_code(codes)

    # from xi'an to chengdu 
    to_flights = flight.find_by_where('Xi\'an', 'Chengdu')
    codes = to_flights.map(&:flight_code)
    # codes = []
    # to_flights.each do |f|
    #   codes << f.flight_code
    # end
    to_combine = flight_price.find_by_combine(params[:type], params[:date], codes)
    to_flight_price = to_combine[:flights]
    codes = to_flight_price.map(&:flight_code)
    # codes = []
    # to_flight_price.each do |f|
    #   codes << f.flight_code
    # end
    to_flights = flight.in_code(codes)
    {
      from_price: from_combine[:price],
      from_flights: from_flights,
      to_price: to_combine[:price],
      to_flights: to_flights
    }
  end

  # POST /flights
  # POST /flights.json
  def create
    @flight = Flight.new(flight_params)

    respond_to do |format|
      if @flight.save
        format.html { redirect_to @flight, notice: 'Flight was successfully created.' }
        format.json { render :show, status: :created, location: @flight }
      else
        format.html { render :new }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flights/1
  # PATCH/PUT /flights/1.json
  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to @flight, notice: 'Flight was successfully updated.' }
        format.json { render :show, status: :ok, location: @flight }
      else
        format.html { render :edit }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1
  # DELETE /flights/1.json
  def destroy
    @flight.destroy
    respond_to do |format|
      format.html { redirect_to flights_url, notice: 'Flight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
      # @flight_price = FlightPrice.where("flight_code": @flight.flight_code)
      @flight_price = FlightPrice.new
      @flight_price = @flight_price.find_by_code(@flight.flight_code)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flight_params
      params.require(:flight).permit(:flight_code, :sched, :from, :to)
    end
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/_form.html.erb
<%= form_with(model: flight, local: true) do |form| %>
  <% if flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
      <% flight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :flight_code %>
    <%= form.text_field :flight_code %>
  </div>

  <div class="field">
    <%= form.label :sched %>
    <%= form.text_field :sched %>
  </div>

  <div class="field">
    <%= form.label :from %>
    <%= form.text_field :from %>
  </div>

  <div class="field">
    <%= form.label :to %>
    <%= form.text_field :to %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/flights/edit.html.erb
<h1>Editing Flight</h1>

<%= render 'form', flight: @flight %>

<%= render 'form2', flight: @flight %>

<%= link_to 'Show', @flight %> |
<%= link_to 'Back', flights_path %>

app/views/flights/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Flights</h1>

<table>
  <thead>
    <tr>
      <th>Fight code</th>
      <th>Sched</th>
      <th>From</th>
      <th>To</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flights.each do |flight| %>
      <tr>
        <td><%= flight.flight_code %></td>
        <td><%= flight.sched %></td>
        <td><%= flight.from %></td>
        <td><%= flight.to %></td>
        <td><%= link_to 'Show', flight %></td>
        <td><%= link_to 'Edit', edit_flight_path(flight) %></td>
        <td><%= link_to 'Destroy', flight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Flight', new_flight_path %>


<br>
<br>
<br>
<h1>Search</h1>

<%= form_tag("/flights/search", method: "get") do %>
<p>
  <%= label_tag(:date, "Date:") %>
  <%= text_field_tag(:date) %>
</p>
<p>
  <%= label_tag(:type, "Type:") %>
  <%= select_tag(:type, options_for_select([['reward','reward'], ['regular','regular']])) %>
</p>
<p>
  <%= submit_tag("Search") %>
</p>
<% end %>

app/views/flights/new.html.erb
<h1>New Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Back', flights_path %>

app/views/flights/search.html.erb
<h1>去程</h1>
<table>
  <thead>
    <tr>
      <th>Fight code</th>
      <th>Sched</th>
      <th>From</th>
      <th>To</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order[:from_flights].each do |flight| %>
      <tr>
        <td><%= flight.flight_code %></td>
        <td><%= flight.sched %></td>
        <td><%= flight.from %></td>
        <td><%= flight.to %></td>
        <td><%= @order[:from_price] %></td>
        <td><%= link_to 'Show', flight %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<h1>返程</h1>
<table>
  <thead>
    <tr>
      <th>Fight code</th>
      <th>Sched</th>
      <th>From</th>
      <th>To</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order[:to_flights].each do |flight| %>
      <tr>
        <td><%= flight.flight_code %></td>
        <td><%= flight.sched %></td>
        <td><%= flight.from %></td>
        <td><%= flight.to %></td>
        <td><%= @order[:to_price] %></td>
        <td><%= link_to 'Show', flight %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'Back', flights_path %>

app/views/flights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Flight code:</strong>
  <%= @flight.flight_code %>
</p>

<p>
  <strong>Sched:</strong>
  <%= @flight.sched %>
</p>

<p>
  <strong>From:</strong>
  <%= @flight.from %>
</p>

<p>
  <strong>To:</strong>
  <%= @flight.to %>
</p>


<h2>Flight Price</h2>
 <p>
  <strong>Weekdays regular:</strong>
  ¥<%= @flight_price.weekdays_regular %>
</p>

<p>
  <strong>Weekdays reward:</strong>
  ¥<%= @flight_price.weekdays_reward %>
</p>

<p>
  <strong>Weekends regular:</strong>
  ¥<%= @flight_price.weekends_regular %>
</p>

<p>
  <strong>Weekends reward:</strong>
  ¥<%= @flight_price.weekends_reward %>
</p>




<%= link_to 'Edit', edit_flight_path(@flight) %> |
<%= link_to 'Back', flights_path %>