config/routes.rb
Rails.application.routes.draw do
  get 'flights/search'
  resources :flight_prices
  resources :flights do
    # resources :flight_prices
  end
  resources :users
  get 'welcome/index'
  get 'articles/new'
  get 'articles/download'
  get 'articles/preview'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :articles do
    resources :comments
  end
  root 'welcome#index'
end

app/models/article.rb
class Article < ApplicationRecord
  include Mongoid::Document

  # has_many :comments, class_name => 'Comment'
  field :title, type: String
  field :text, type: String
  field :pdf_url, type: String
  validates :title, presence: true,
                    length: { minimum: 5}
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def new
    print 'new'
  end

  def edit
    @article = Article.find(params[:id])
  end

  def download
    @article = Article.find(params[:format])
    if @article == nil?
      render 'show'
    else
      file_path = @article.pdf_url
      # send_file file_path
      if File.exist?(file_path)
        io = File.open(file_path)
        io.binmode
        send_data(io.read, :filename => 'childs.pdf', :disposition => 'attachment')
        io.close
      else
        print '文件不存在'
        render 'show'
      end
    end
  end

  def preview
    @article = Article.find(params[:format])
    if @article == nil?
      render 'show'
    else
      binding.pry
      file_path = @article.pdf_url
      io = File.open(file_path)
      io.binmode
      #文档
      data = io.read
      io.close
      return data
    end
  end

  def create
    # 参数映射
    # render plain: params[:article].inspect
    # @article = Article.new(params[:article])
    @product = article_params
    # @article = Article.new(article_params)
    unless request.get?
      filename = uploadfile(@product[:pdf_url])
      if filename
        @product[:pdf_url] = filename

        @article = Article.new(@product)
        # binding.pry

        if @article.save
          redirect_to @article
        else
          render 'new'
        end
      else
        render 'new'
      end
    end
    # redirect_to search_path
  end

  def show
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

 def destroy
   @article = Article.find(params[:id])
   @article.destroy

   redirect_to articles_path
 end


  private

  def article_params
    params.require(:article).permit(:title, :text, :pdf_url)
  end

  def uploadfile(file)
    if !file.original_filename.empty?
      if file.content_type == 'application/pdf'
        @filename = file.original_filename
        #设置目录路径，如果目录不存在，生成新目录
        @pdf_path="#{Rails.root}/public/upload/#{Time.now.to_i}"
        FileUtils.mkdir(@pdf_path) unless File.exist?(@pdf_path)
        #写入文件
        ##wb 表示通过二进制方式写，可以保证文件不损坏
        File.open(@pdf_path + "/#{@filename}", 'wb') do |f|
          f.write(file.read)
        end
        return @pdf_path + "/#{@filename}"
      else
        print '文件格式不对'
        return nil
      end
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= form_with(model: @article, local: true) do |form| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<td><%= link_to 'New article', new_article_path %></td>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
<!--      article_path(article) 路径-->
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Back', articles_path %></td>
      <td><%= link_to 'Destroy', article_path(article),
                      method: :delete,
                      data: { confirm: 'Are you sure?' } %></td>
      <td><%= link_to 'Preview', articles_preview_path(article) %></td>
      <td><%= link_to 'DownLoad', articles_download_path(article) %></td>
<!--      <td><%#= link_to 'My blog', controller: 'welcome' %></td>-->
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>new articles</h1>

<%= form_with scope: :article, url: articles_path, local: true do |form| %>

  <%# if @article.errors.any? %>
<!--    <div id="error_explanation">-->
<!--      <h2>-->
<!--        <%#= pluralize(@article.errors.count, "error") %> prohibited-->
<!--        this article from being saved:-->
<!--      </h2>-->
<!--      <ul>-->
        <%# @article.errors.full_messages.each do |msg| %>
<!--          <li><%#= msg %></li>-->
        <%# end %>
<!--      </ul>-->
<!--    </div>-->
  <%# end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    图片上传<br>
    <%= form.file_field :pdf_url, :accept =>'.pdf'%>
  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.1.erb
<p>
  <strong>Titles:</strong>
  <%=@article.title %>
</p>
<p>
  <strong>Text:</strong>
  <%=@article.text %>
</p>


<h2>Comments</h2>
<% @article.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
<% end %>

<h2>Add a comment:</h2>
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/articles/show.html.erb
<p>
  <strong>Titles:</strong>
  <%=@article.title %>
</p>
<p>
  <strong>Text:</strong>
  <%=@article.text %>
</p>