config/routes.rb
Rails.application.routes.draw do
  get 'flights/search'
  resources :flight_prices
  resources :flights do
    # resources :flight_prices
  end
  resources :users
  get 'welcome/index'
  get 'articles/new'
  get 'articles/download'
  get 'articles/preview'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :articles do
    resources :comments
  end
  root 'welcome#index'
end

app/models/flight_price.rb
class FlightPrice
  include Mongoid::Document
  require 'date'
  belongs_to :flight, :class_name => 'Flight', optional: true

  field :weekdays_regular, type: String
  field :weekdays_reward, type: String
  field :weekends_regular, type: String
  field :weekends_reward, type: String
  field :flight_code, type: String

  def find_by_combine(type, date, codes)
    my_field = convert_params(type, date)
    flight = FlightPrice.in(flight_code: codes).order_by("#{my_field}": :asc).first
    price = flight["#{my_field}"]
    flights = FlightPrice.where("#{my_field}": price).in(flight_code: codes)
    {
      price: price,
      flights: flights
    }
  end

  def find_by_code(code)
    FlightPrice.find_by("flight_code": code)
  end

  private

  def convert_params(type, date)
    wday = Date.strptime(date, '%Y%m%d').wday
    is_workday = (1..5).include?(wday)
    if type == 'reward' && is_workday
      my_field = 'weekdays_reward'
    elsif type == 'regular' && is_workday
      my_field = 'weekdays_regular'
    elsif type == 'reward' && !is_workday
      my_field = 'weekends_reward'
    elsif type == 'regular' && !is_workday
      my_field = 'weekends_regular'
    end
    my_field
  end
end

app/controllers/flight_prices_controller.rb
class FlightPricesController < ApplicationController
  before_action :set_flight_price, only: [:show, :edit, :update, :destroy]

  # GET /flight_prices
  # GET /flight_prices.json
  def index
    @flight_prices = FlightPrice.all
  end

  # GET /flight_prices/1
  # GET /flight_prices/1.json
  def show
  end

  # GET /flight_prices/new
  def new
    @flight_price = FlightPrice.new
  end

  # GET /flight_prices/1/edit
  def edit
  end

  # POST /flight_prices
  # POST /flight_prices.json
  def create
    @flight_price = FlightPrice.new(flight_price_params)
    # binding.pry
    respond_to do |format|
      if @flight_price.save
        format.html { redirect_to @flight_price, notice: 'Flight price was successfully created.' }
        format.json { render :show, status: :created, location: @flight_price }
      else
        format.html { render :new }
        format.json { render json: @flight_price.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flight_prices/1
  # PATCH/PUT /flight_prices/1.json
  def update
    respond_to do |format|
      if @flight_price.update(flight_price_params)
        format.html { redirect_to @flight_price, notice: 'Flight price was successfully updated.' }
        format.json { render :show, status: :ok, location: @flight_price }
      else
        format.html { render :edit }
        format.json { render json: @flight_price.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flight_prices/1
  # DELETE /flight_prices/1.json
  def destroy
    @flight_price.destroy
    respond_to do |format|
      format.html { redirect_to flight_prices_url, notice: 'Flight price was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight_price
      @flight_price = FlightPrice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flight_price_params
      params.require(:flight_price).permit(:weekdays_regular, :weekdays_reward, :weekends_regular, :weekends_reward, :flight_code)
    end
end

app/helpers/flight_prices_helper.rb
module FlightPricesHelper
end

app/views/flight_prices/_form.html.erb
<%= form_with(model: flight_price, local: true) do |form| %>
  <% if flight_price.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flight_price.errors.count, "error") %> prohibited this flight_price from being saved:</h2>

      <ul>
      <% flight_price.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :weekdays_regular %>
    <%= form.text_field :weekdays_regular %>
  </div>

  <div class="field">
    <%= form.label :weekdays_reward %>
    <%= form.text_field :weekdays_reward %>
  </div>

  <div class="field">
    <%= form.label :weekends_regular %>
    <%= form.text_field :weekends_regular %>
  </div>

  <div class="field">
    <%= form.label :weekends_reward %>
    <%= form.text_field :weekends_reward %>
  </div>

  <div class="field">
    <%= form.label :flight_code %>
    <%= form.text_field :flight_code %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/flight_prices/edit.html.erb
<h1>Editing Flight Price</h1>

<%= render 'form', flight_price: @flight_price %>

<%= link_to 'Show', @flight_price %> |
<%= link_to 'Back', flight_prices_path %>

app/views/flight_prices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Flight Prices</h1>

<table>
  <thead>
    <tr>
      <th>Weekdays regular</th>
      <th>Weekdays reward</th>
      <th>Weekends regular</th>
      <th>Weekends reward</th>
      <th>Fight code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flight_prices.each do |flight_price| %>
      <tr>
        <td>¥<%= flight_price.weekdays_regular %></td>
        <td>¥<%= flight_price.weekdays_reward %></td>
        <td>¥<%= flight_price.weekends_regular %></td>
        <td>¥<%= flight_price.weekends_reward %></td>
        <td><%= flight_price.flight_code %></td>
        <td><%= link_to 'Show', flight_price %></td>
        <td><%= link_to 'Edit', edit_flight_price_path(flight_price) %></td>
        <td><%= link_to 'Destroy', flight_price, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Flight Price', new_flight_price_path %>

app/views/flight_prices/new.html.erb
<h1>New Flight Price</h1>

<%= render 'form', flight_price: @flight_price %>

<%= link_to 'Back', flight_prices_path %>

app/views/flight_prices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Weekdays regular:</strong>
  ¥<%= @flight_price.weekdays_regular %>
</p>

<p>
  <strong>Weekdays reward:</strong>
  ¥<%= @flight_price.weekdays_reward %>
</p>

<p>
  <strong>Weekends regular:</strong>
  ¥<%= @flight_price.weekends_regular %>
</p>

<p>
  <strong>Weekends reward:</strong>
  ¥<%= @flight_price.weekends_reward %>
</p>

<p>
  <strong>Fight code:</strong>
  <%= @flight_price.flight_code %>
</p>

<%= link_to 'Edit', edit_flight_price_path(@flight_price) %> |
<%= link_to 'Back', flight_prices_path %>